---
django_environment:
    DEBUG: false
    SECRET_KEY: "{{ lookup('aws_ssm', '/site/SECRET_KEY') }}"
    EMAIL_HOST: email-smtp.us-east-1.amazonaws.com
    EMAIL_HOST_USER: "{{ lookup('aws_ssm', '/site/EMAIL_HOST_USER') }}"
    EMAIL_HOST_PASSWORD: "{{ lookup('aws_ssm', '/site/EMAIL_HOST_PASSWORD') }}"
    DATABASE_URL: "{{ lookup('aws_ssm', '/site/DATABASE_URL') }}"
    CACHE_URL: "{{ lookup('aws_ssm', '/site/CACHE_URL') }}"
    RRL_REDIS_HOST: "{{ lookup('aws_ssm', '/site/RRL_REDIS_HOST') }}"
    SENTRY_DSN: "{{ lookup('aws_ssm', '/site/SENTRY_DSN') }}"
    RECAPTCHA_PUBLIC_KEY: "{{ lookup('aws_ssm', '/site/RECAPTCHA_PUBLIC_KEY_V2') }}"
    RECAPTCHA_PRIVATE_KEY: "{{ lookup('aws_ssm', '/site/RECAPTCHA_PRIVATE_KEY_V2') }}"
    NEW_RELIC_LICENSE_KEY: "{{ lookup('aws_ssm', '/site/NEWRELIC_INI_KEY') }}"
    NEW_RELIC_APP_NAME: "openstates.org"

# postgres
pg_password: "{{ lookup('aws_ssm', '/bobsled/backups/PGPASSWORD') }}"
pg_host: "{{ lookup('aws_ssm', '/bobsled/backups/PGHOST') }}"
pg_user: "{{ lookup('aws_ssm', '/bobsled/backups/PGUSER') }}"
pg_port: 5432
pg_database: openstatesorg
